### ISSUE TITLE
Remodel api-gateway CR to support many authn

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/api-gateway#31]
After brainstorming and consulting with Compass team there's a need to support more than one authenticator. Also it is a good time to refactor it too.

```
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: oauth
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  authn:
    - name: OAUTH
      config:
        bar: foo
    - name: JWT
      config:
        foo: bar
  paths:
  - path: /headers
    scopes: [read]
    methods: [GET]
  - path: /images
    scopes: [write]
    methods: [POST]
  mutators: []
```

**Comment by Demonsthere** [comment]
New CR form:
```yaml
---
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: sample
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  rules:
    - path: /foo
      methods: [GET,POST]
      accessStrategy:
        - OAUTH
        - JWT
      mutators: []
    - path: /bar
      scopes: []
      methods: [GET]
      accessStrategy: 
        - OAUTH
            scopes: "foo bar"
        - JWT
            scopes: "a b c"
            truested_issuer: "http://"
      mutators: 
        - id_token:
            config
    - path: /aaaaa
      methods: [GET]
      accessStrategy: 
        - OAUTH
            scopes: "foo bar"
    - path: /.*
      methods: [GET,POST,....] (to omija oathkeepera, bo nie ma mutatorów.)
      accessStrategy: 
        - ALLOW
```
